# Generated by Django 4.1.2 on 2022-11-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryTrough',
            new_name='categoryType',
        ),
    ]
