# Generated by Django 4.1.2 on 2022-11-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_categorytrough_postcategory_categorytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryType',
            new_name='category',
        ),
    ]
