# Generated by Django 4.1.2 on 2022-11-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_commentpost_postcategory_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribes',
            new_name='subscribers',
        ),
    ]
