# Generated by Django 4.1.2 on 2022-11-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_subscribes_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoryType',
            new_name='category',
        ),
    ]
